#define WINDOW_WIDTH 400
#define WINDOW_HEIGHT 300
#define PLAYER_SIDE_LENGTH 30
#define PLAYER_SPEED 40.0

#define PLAYER_POS_X (WINDOW_WIDTH / 2 - PLAYER_SIDE_LENGTH / 2)
#define PLAYER_POS_Y (WINDOW_HEIGHT / 2 - PLAYER_SIDE_LENGTH / 2)

#define FPS 30
#define FRAME_TARGET_TIME (1000 / FPS)
 